#!/bin/bash
# This script will start a Mongo database and store the data in
# local data files. It is expecting a Docker engine to be running.
#
# Usage:  ./stop-mongo
#
if [ -e "mongo-container.id" ] ; then
  docker stop `cat mongo-container.id`
  docker ps
else
  echo "Error: could not find the container ID to stop - Docker ps to find it."
fi
