version: '3'

services:
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - mongo

  mongo:
    image: 'mongo:3.4'
    ports:
      - '0.0.0.0:27017:27017'
    volumes:
      - 'mongo-data:/data/db'
volumes:
  mongo-data: {}