#!/bin/bash
# This script will start a MySQL database and store the data in
# local data files. It is expecting a Docker engine to be running.
#
# Usage:  ./stop-mysql
#
if [ -e "mysql-container.id" ] ; then
  docker stop `cat mysql-container.id`
  docker ps
else
  echo "Error: could not find the container ID to stop - Docker ps to find it."
fi
