version: '2'
services:
  node:
    image: node:boron
    command: sh -c "npm install && npm start"
    working_dir: /app
    ports:
      - "8080:8080"
    volumes:
      - .:/app
  mongo:
    image: mongo:3.5.13
    ports:
      - "27017:27017"
    volumes:
      - "mongo_data:/data/db"
volumes:
  mongo_data: {}
